// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Films            string
	Planets          string
	PlanetsFilms     string
	SchemaMigrations string
}{
	Films:            "films",
	Planets:          "planets",
	PlanetsFilms:     "planets_films",
	SchemaMigrations: "schema_migrations",
}
